stages:
    - build
    - test
    - deploy

build-job:
    stage: build
    script:
        - docker build -t nuxt-docker-test app/.

test-job:
    stage: test
    script:
        - echo "DOCKER BUILD PASSED"
        - echo "last push by $GITLAB_USER_LOGIN"
        - echo "on branch $CI_COMMIT_BRANCH"

deploy-job:
    stage: deploy
    script:
        - docker run -d -p 5000:5000 --rm app/nuxt-docker-test
