image:
    ubuntu:20.04

stages:
    - build
    - deploy

build_job:
    stage: build
    script:
        - docker build -t nuxt-docker-test app/.

deploy_job:
    stage: deploy
    needs: [build_job]
    script:
        - docker run -d -p 5000:5000 --rm app/nuxt-docker-test
